### ISSUE TITLE
TASK [mariadb : StartMariaDB10.2 Service]  error

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-databases_el#5]
TASK [mariadb : StartMariaDB10.2 Service] 
fatal: [40.117.91.128]: FAILED! => {"changed": false, "msg": "Unable to start service mariadb: Job for mariadb.service failed because the control process exited with error code. See \"systemctl status mariadb.service\" and \"journalctl -xe\" for details.\n"}

mariadb.service - MariaDB 10.2.25 database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Sun 2019-07-07 09:24:57 UTC; 2min 40s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 86182 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 86014 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1 (code=exited, status=0/SUCCESS)
  Process: 86012 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
 Main PID: 86182 (code=exited, status=1/FAILURE)

**Comment by hliblack** [comment]
初始化安装步骤出错，没有生成mysql数据库

**Comment by chendelin1982** [comment]
增加生成mysql数据库的 task
